### ISSUE TITLE
Fails to install on QGIS 3.2.0-Bonn

### ISSUE THREAD

**Issue by Shujee** [gingerik/qgsAffine#10]
An error occurred during execution of following code:
pyplugin_installer.instance().installFromZipFile(r'C:\Users\<UserName>\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\TempState\Downloads\qgsAffine-master (1).zip')

traceback.print_exception() failed

Python version:

QGIS version:
3.2.0-Bonn 'Bonn', bc43194061

Python path:

**Comment by jerryhall** [comment]
I'm having similar issue, cannot install into QGIS 3.02. I get this error messaging: 

Couldn't load plugin 'qgsAffine' due to an error when calling its classFactory() method 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Jerry/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgsAffine\__init__.py", line 35, in classFactory
    from qgsAffine import qgsAffine
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Jerry/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgsAffine\qgsAffine.py", line 124
    print vlayer.name()
               ^
SyntaxError: invalid syntax

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.2-Girona Girona, 307d082e3d

**Comment by jerryhall** [comment]
I learned the plugin only works up to QGIS v2.99 so installed a legacy version of QGIS and the plugin works great. Thanks!

**Comment by ianengelbrecht** [comment]
Would be great if this could be upgraded to work with QGIS 3
